require('dotenv').config()

STORAGE_PATH = process.env.STORAGE_PATH
TOKEN_FILE_NAME = 'token.json'
TOKEN_FILE_PATH = `${STORAGE_PATH}/${TOKEN_FILE_NAME}`
DROPBOX_FOLDER = process.env.DROPBOX_FOLDER
DROPBOX_BACKUP_FOLDER = process.env.DROPBOX_BACKUP_FOLDER
FROM_MAIL = process.env.FROM_MAIL
TO_MAIL = process.env.TO_MAIL

module.exports = { STORAGE_PATH, TOKEN_FILE_NAME, TOKEN_FILE_PATH, DROPBOX_FOLDER, DROPBOX_BACKUP_FOLDER, FROM_MAIL, TO_MAIL }
